version: '3'

volumes:
  redis_data:
  pg_data:
  static:

services:
  db1:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db1
    volumes:
      - static:/backend_static/
  
  nginx:
    build: ./nginx
    ports:
      - "8001:80"
    depends_on:
      - backend
    volumes:
      - static:/staticfiles/