# Generated by Django 4.2.8 on 2024-02-26 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('description', models.TextField(max_length=150, verbose_name='описание')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'вещь',
                'verbose_name_plural': 'вещи',
            },
        ),
    ]
